### ISSUE TITLE
RubyNLP

### ISSUE THREAD

**Issue by arbox** [lfcipriani/punkt-segmenter#7]
Dear Luis,

I've recently added your project to our RubyNLP list: https://github.com/arbox/nlp-with-ruby

I wonder if you want to participate in the Ruby for NLP network. You could do this in a very simple step by adding the `rubynlp` topic to your GitHub repository. 

Thank you for the project!

**Comment by lfcipriani** [comment]
Hi @arbox,

Topic is added, thanks for organizing this list! :-)

**Comment by arbox** [comment]
You're welcome! Use the list, make it useful for others! Thank you for your project and contributions!
